[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://portfolio-b7nz.onrender.com"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
