/**
 * Backwards-compatible barrel — delegates to domain-separated files in ./portfolio/.
 * Consuming components continue to import from "@/hooks/use-portfolio" unchanged.
 */
export {
  useProjects,
  useSkills,
  useSkillConnections,
  useMindset,
  useArticles,
  useArticle,
  useArticleSearch,
  useArticleReactions,
  useReactToArticle,
  useExperiences,
  useServices,
  useTestimonials,
  useMessages,
  useSendMessage,
  useLogin,
  useAuth,
  useAnalyticsSummary,
  useVitalsSummary,
  useEmailTemplates,
  useGuestbook,
  useSubmitGuestbook,
  useReactToGuestbook,
  useAdminMindset,
  useAdminGuestbook,
  useApproveGuestbook,
  useDeleteGuestbook,
  useAdminExperiences,
  useAdminServices,
  useAdminSkills,
  useAdminProjects,
  useProjectById,
  useSubscribe,
  useUnsubscribe,
} from "./portfolio";
