import React from 'react';
import ReactPDF, { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { logger } from '../lib/logger.js';

// Define styles for PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#334155',
  },
  header: {
    marginBottom: 20,
    borderBottom: '1pt solid #e2e8f0',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4f46e5',
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 4,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  summaryText: {
    lineHeight: 1.6,
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 4,
    marginVertical: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableHeader: {
    backgroundColor: '#f8fafc',
    fontSize: 9,
    fontWeight: 'bold',
  },
  tableCell: {
    padding: 8,
    flex: 1,
  },
  milestoneTitle: {
    fontWeight: 'bold',
    fontSize: 11,
    color: '#1e293b',
  },
  milestoneDuration: {
    fontSize: 9,
    color: '#4f46e5',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#94a3b8',
    borderTop: '1pt solid #f1f5f9',
    paddingTop: 10,
  },
});

interface EstimateData {
  name: string;
  projectType: string;
  estimation: {
    summary: string;
    hours: { min: number; max: number };
    cost: { min: number; max: number; currency: string };
    milestones: { title: string; duration: string; description: string }[];
    techSuggestions: string[];
  };
}

const EstimateDocument = ({ data }: { data: EstimateData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Project Scope Estimate</Text>
        <Text style={styles.subtitle}>Prepared for: {data.name} | {data.projectType}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.summaryText}>{data.estimation.summary}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Budget & Timeline</Text>
        <View style={styles.table}>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={styles.tableCell}>Item</Text>
            <Text style={{ ...styles.tableCell, textAlign: 'right' }}>Estimation</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableCell}>Estimated Hours</Text>
            <Text style={{ ...styles.tableCell, textAlign: 'right' }}>{data.estimation.hours.min} - {data.estimation.hours.max} hrs</Text>
          </View>
          <View style={[styles.tableRow, { borderBottomWidth: 0 }]}>
            <Text style={styles.tableCell}>Estimated Cost</Text>
            <Text style={{ ...styles.tableCell, textAlign: 'right', color: '#4f46e5', fontWeight: 'bold' }}>
               {data.estimation.cost.min.toLocaleString()} - {data.estimation.cost.max.toLocaleString()} {data.estimation.cost.currency}
            </Text>
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Project Milestones</Text>
        {data.estimation.milestones.map((m, i) => (
          <View key={i} style={{ marginBottom: 12 }}>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 2 }}>
              <Text style={styles.milestoneTitle}>{m.title}</Text>
              <Text style={styles.milestoneDuration}>{m.duration}</Text>
            </View>
            <Text style={{ fontSize: 9, lineHeight: 1.4 }}>{m.description}</Text>
          </View>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Recommended Tech Stack</Text>
        <Text style={styles.summaryText}>{data.estimation.techSuggestions.join(' • ')}</Text>
      </View>

      <Text style={styles.footer}>
        This estimate was generated by AI based on the provided project description.
        Final scope and pricing may vary upon detailed technical discovery.
      </Text>
    </Page>
  </Document>
);

export class PdfService {
  async generateScopeEstimate(data: EstimateData): Promise<Buffer> {
    try {
      const buffer = await ReactPDF.renderToBuffer(<EstimateDocument data={data} />);
      return buffer;
    } catch (error) {
      logger.error({ error, data }, 'Failed to generate PDF');
      throw error;
    }
  }
}

export const pdfService = new PdfService();
