-- Migration: 0029_rebuild_site_settings.sql
-- Force recreation of site_settings to match the shared schema exactly.
-- This is necessary because incremental migrations have drifted or failed 
-- to add the 50+ columns now required by the current application version.

DROP TABLE IF EXISTS "site_settings" CASCADE;

CREATE TABLE "site_settings" (
    "id" serial PRIMARY KEY NOT NULL,
    "isOpenToWork" boolean DEFAULT true NOT NULL,
    "availabilityStatus" varchar(255),
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "personalName" varchar(255) DEFAULT 'Your Name',
    "personalTitle" varchar(255) DEFAULT 'Full Stack Developer',
    "personalBio" text DEFAULT 'Passionate about building amazing products',
    "personalAvatar" varchar(500),
    "resumeUrl" varchar(500),
    "whyHireMeData" jsonb,
    "aboutAvailability" varchar(255) DEFAULT 'Open to Work',
    "aboutDescription" text DEFAULT 'Building scalable web systems and analyzing complex algorithms.',
    "aboutTechStack" jsonb DEFAULT '["React", "Node.js", "TypeScript", "PostgreSQL", "Tailwind"]'::jsonb,
    "aboutTimeline" jsonb DEFAULT '[{"year": "2024 - Present", "title": "Advanced System Design", "description": "Deep diving into distributed systems, Docker, and Microservices architecture."}, {"year": "2023", "title": "Engineering Core", "description": "Mastering Data Structures, Algorithms, and OOP at Tribhuvan University."}, {"year": "2022", "title": "Hello World", "description": "Started the journey with Python scripting and basic web development."}]'::jsonb,
    "aboutInfoCards" jsonb DEFAULT '[{"icon": "GraduationCap", "label": "Status", "value": "B.E. Student"}, {"icon": "Code", "label": "Focus Area", "value": "Full Stack System Design", "color": "purple"}, {"icon": "Cpu", "label": "Hardware", "value": "Electronics & Comms", "color": "purple"}, {"icon": "Target", "label": "Goal", "value": "Software Engineer"}]'::jsonb,
    "socialGithub" varchar(500),
    "socialLinkedin" varchar(500),
    "socialTwitter" varchar(500),
    "socialInstagram" varchar(500),
    "socialFacebook" varchar(500),
    "socialYoutube" varchar(500),
    "socialDiscord" varchar(500),
    "socialStackoverflow" varchar(500),
    "socialDevto" varchar(500),
    "socialMedium" varchar(500),
    "socialEmail" varchar(255),
    "personalPhone" varchar(255),
    "locationText" varchar(255) DEFAULT 'Kathmandu, Nepal',
    "chatbotGreeting" text DEFAULT 'Hi there! I''m Abdhesh''s AI assistant. How can I help you today?',
    "heroGreeting" varchar(255) DEFAULT 'Hey, I am',
    "heroBadgeText" varchar(255) DEFAULT 'Available for work',
    "heroTaglines" jsonb DEFAULT '["Building amazing products", "Solving complex problems"]'::jsonb,
    "heroCtaPrimary" varchar(255) DEFAULT 'View My Work',
    "heroCtaPrimaryUrl" varchar(255) DEFAULT '#projects',
    "heroCtaSecondary" varchar(255) DEFAULT 'Get In Touch',
    "heroCtaSecondaryUrl" varchar(255) DEFAULT '#contact',
    "logoText" varchar(255) DEFAULT 'Portfolio.Dev',
    "heroHeadingLine1" varchar(255) DEFAULT 'Start building',
    "heroHeadingLine2" varchar(255) DEFAULT 'The Future',
    "navbarLinks" jsonb DEFAULT '[]'::jsonb,
    "footerCopyright" varchar(255) DEFAULT '© 2024 Your Name. All rights reserved.',
    "footerTagline" varchar(500) DEFAULT 'Building the future, one line of code at a time.',
    "sectionOrder" jsonb DEFAULT '["hero", "about", "projects", "skills", "experience", "contact"]'::jsonb,
    "sectionVisibility" jsonb DEFAULT '{"hero": true, "about": true, "projects": true, "skills": true, "whyhireme": true, "services": true, "mindset": true, "practice": true, "experience": true, "testimonials": true, "guestbook": true, "contact": true}'::jsonb,
    "availabilitySlots" jsonb DEFAULT '[]'::jsonb,
    "featureBlog" boolean DEFAULT true NOT NULL,
    "featureGuestbook" boolean DEFAULT true NOT NULL,
    "featureTestimonials" boolean DEFAULT true NOT NULL,
    "featureServices" boolean DEFAULT true NOT NULL,
    "featurePlayground" boolean DEFAULT false NOT NULL,
    "aboutHeading" varchar(255) DEFAULT 'About Me',
    "projectsHeading" varchar(255) DEFAULT 'Flagship Projects',
    "skillsHeading" varchar(255) DEFAULT 'Technical Arsenal',
    "whyHireMeHeading" varchar(255) DEFAULT 'Why Hire Me',
    "servicesHeading" varchar(255) DEFAULT 'What I Do',
    "mindsetHeading" varchar(255) DEFAULT 'Engineering Mindset',
    "practiceHeading" varchar(255) DEFAULT 'Disciplined Practice',
    "experienceHeading" varchar(255) DEFAULT 'Professional Journey',
    "testimonialsHeading" varchar(255) DEFAULT 'Client Feedback',
    "guestbookHeading" varchar(255) DEFAULT 'Guestbook',
    "contactHeading" varchar(255) DEFAULT 'Get In Touch'
);
